#!/bin/sh

. "$(dirname "$(readlink -f "$0")")/libwrapper.sh" || exit

cc_check_args "${@}"

cc_add_target_clang
cc_add_target_reproducible
cxx_add_target_extra
cc_add_target_ld_args
cc_add_fortify
cc_add_pie
cc_add_glibcxx
cxx_add_target_icecc clang

wrapper_exec "$@"
